### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by joshgrift** [wflosin/Assignment-Progress#1]
Having trouble understanding how to install and run. I've cloned the repository and run `python3 AssignmentProgress.py`. I get the following error:
```
ModuleNotFoundError: No module named 'pygame'
```
I'm getting an error when I pip install this, so not sure if that's the next step.

**Comment by wflosin** [comment]
I made it into an executable to run it (although its weird that installing pygame raises an error), so here are the steps I took
1. `pip install pyinstaller`
2. navigate to the file where the repository is
3. run `pyinstaller --noconsole AssignmentProgress.py`
4. The .exe should be in the created "dist" folder.

**Comment by joshgrift** [comment]
Personally running on a linux machine. I'll see if I can get pygame installed manually. Think it could work that way?

**Comment by joshgrift** [comment]
Got it working. Had to `sudo apt-get install python3-pygame` instead of `pip install pygame`.
